#!/usr/bin/env bash
# Regenerates the .webp siblings and _data/imagesizes.yml after adding images.
# Needs cwebp: brew install webp
set -e
cd "$(dirname "$0")/.."
tmp=$(mktemp)
find assets/imgs -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' \) | sort | while read -r f; do
  w=$(sips -g pixelWidth "$f" | awk '/pixelWidth/{print $2}')
  h=$(sips -g pixelHeight "$f" | awk '/pixelHeight/{print $2}')
  [ -z "$w" ] && continue
  echo "\"/$f\": { w: $w, h: $h }" >> "$tmp"
  out="${f%.*}.webp"
  if [ "$out" -nt "$f" ]; then continue; fi
  if [ "$w" -gt 2000 ]; then
    cwebp -quiet -q 80 -m 6 -metadata none -resize 2000 0 "$f" -o "$out"
  else
    cwebp -quiet -q 80 -m 6 -metadata none "$f" -o "$out"
  fi
done
{ echo "# generated by script/images.sh"; sort "$tmp"; } > _data/imagesizes.yml
rm -f "$tmp"
echo "$(find assets/imgs -name "*.webp" | wc -l | tr -d " ") webp files, $(grep -c "^\"" _data/imagesizes.yml) size entries"
